package com.amazonaws.sfc.canbus.jna;

import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * struct bcm_msg_head - head of messages to/from the broadcast manager<br>
 * @opcode:    opcode, see enum below.<br>
 * @flags:     special flags, see below.<br>
 * @count:     number of frames to send before changing interval.<br>
 * @ival1:     interval for the first @count frames.<br>
 * @ival2:     interval for the following frames.<br>
 * @can_id:    CAN ID of frames to be sent or received.<br>
 * @nframes:   number of frames appended to the message head.<br>
 * @frames:    array of CAN frames.<br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a> */
public class bcm_msg_head extends Structure {
	/** C type : __u32 */
	public int opcode;
	/** C type : __u32 */
	public int flags;
	/** C type : __u32 */
	public int count;
	/** C type : timeval */
	public TimeValue ival1;
	/** C type : timeval */
	public TimeValue ival2;
	/** C type : canid_t */
	public int can_id;
	/** C type : __u32 */
	public int nframes;
	public bcm_msg_head() {
		super();
	}
    public bcm_msg_head(Pointer ptr) {
        super(ptr);
    }
	protected List<String> getFieldOrder() {
		return Arrays.asList("opcode", "flags", "count", "ival1", "ival2", "can_id", "nframes");
	}
	/**
	 * @param opcode C type : __u32<br>
	 * @param flags C type : __u32<br>
	 * @param count C type : __u32<br>
	 * @param ival1 C type : timeval<br>
	 * @param ival2 C type : timeval<br>
	 * @param can_id C type : canid_t<br>
	 * @param nframes C type : __u32<br>
	 */
	@SuppressWarnings({"unused", "SpellCheckingInspection"})
	public bcm_msg_head(int opcode, int flags, int count, TimeValue ival1, TimeValue ival2, int can_id, int nframes) {
		super();
		this.opcode = opcode;
		this.flags = flags;
		this.count = count;
		this.ival1 = ival1;
		this.ival2 = ival2;
		this.can_id = can_id;
		this.nframes = nframes;
	}
    public static class ByReference extends bcm_msg_head implements Structure.ByReference {
		
	};
	public static class ByValue extends bcm_msg_head implements Structure.ByValue {
		
	};
}
