package com.amazonaws.sfc.canbus.jna;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * CAN bus error counters<br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a> */
@SuppressWarnings({"unused", "SpellCheckingInspection"})
public class can_berr_counter extends Structure {
	/** C type : __u16 */
	public short txerr;
	/** C type : __u16 */
	public short rxerr;
	public can_berr_counter() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("txerr", "rxerr");
	}
	/**
	 * @param txerr C type : __u16<br>
	 * @param rxerr C type : __u16
	 */
	public can_berr_counter(short txerr, short rxerr) {
		super();
		this.txerr = txerr;
		this.rxerr = rxerr;
	}
	public static class ByReference extends can_berr_counter implements Structure.ByReference {
		
	};
	public static class ByValue extends can_berr_counter implements Structure.ByValue {
		
	};
}
