package com.amazonaws.sfc.canbus.jna;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * CAN controller mode<br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a> */
@SuppressWarnings({"unused", "SpellCheckingInspection"})
public class can_ctrlmode extends Structure {
	/** C type : __u32 */
	public int mask;
	/** C type : __u32 */
	public int flags;
	public can_ctrlmode() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("mask", "flags");
	}
	/**
	 * @param mask C type : __u32<br>
	 * @param flags C type : __u32
	 */
	public can_ctrlmode(int mask, int flags) {
		super();
		this.mask = mask;
		this.flags = flags;
	}
	public static class ByReference extends can_ctrlmode implements Structure.ByReference {
		
	};
	public static class ByValue extends can_ctrlmode implements Structure.ByValue {
		
	};
}
