package com.amazonaws.sfc.canbus.jna;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * CAN device statistics<br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a> */
@SuppressWarnings({"unused", "SpellCheckingInspection"})
public class can_device_stats extends Structure {
	/**
	 * Bus errors<br>
	 * C type : __u32
	 */
	public int bus_error;
	/**
	 * Changes to error warning state<br>
	 * C type : __u32
	 */
	public int error_warning;
	/**
	 * Changes to error passive state<br>
	 * C type : __u32
	 */
	public int error_passive;
	/**
	 * Changes to bus off state<br>
	 * C type : __u32
	 */
	public int bus_off;
	/**
	 * Arbitration lost errors<br>
	 * C type : __u32
	 */
	public int arbitration_lost;
	/**
	 * CAN controller re-starts<br>
	 * C type : __u32
	 */
	public int restarts;
	public can_device_stats() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("bus_error", "error_warning", "error_passive", "bus_off", "arbitration_lost", "restarts");
	}
	/**
	 * @param bus_error Bus errors<br>
	 * C type : __u32<br>
	 * @param error_warning Changes to error warning state<br>
	 * C type : __u32<br>
	 * @param error_passive Changes to error passive state<br>
	 * C type : __u32<br>
	 * @param bus_off Changes to bus off state<br>
	 * C type : __u32<br>
	 * @param arbitration_lost Arbitration lost errors<br>
	 * C type : __u32<br>
	 * @param restarts CAN controller re-starts<br>
	 * C type : __u32
	 */
	public can_device_stats(int bus_error, int error_warning, int error_passive, int bus_off, int arbitration_lost, int restarts) {
		super();
		this.bus_error = bus_error;
		this.error_warning = error_warning;
		this.error_passive = error_passive;
		this.bus_off = bus_off;
		this.arbitration_lost = arbitration_lost;
		this.restarts = restarts;
	}
	public static class ByReference extends can_device_stats implements Structure.ByReference {
		
	};
	public static class ByValue extends can_device_stats implements Structure.ByValue {
		
	};
}
