package com.amazonaws.sfc.canbus.jna;

import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * CAN clock parameters<br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a> */
@SuppressWarnings({"unused", "SpellCheckingInspection"})
public class can_clock extends Structure {
	/**
	 * CAN system clock frequency in Hz<br>
	 * C type : __u32
	 */
	public int freq;
	public can_clock() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("freq");
	}
	/**
	 * @param freq CAN system clock frequency in Hz<br>
	 * C type : __u32
	 */
	public can_clock(int freq) {
		super();
		this.freq = freq;
	}
	public static class ByReference extends can_clock implements Structure.ByReference {
		
	};
	public static class ByValue extends can_clock implements Structure.ByValue {
		
	};
}
