/* This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a> */

package com.amazonaws.sfc.canbus.jna;

import com.ochafik.lang.jnaerator.runtime.NativeSize;
import com.ochafik.lang.jnaerator.runtime.globals.GlobalInt;
import com.ochafik.lang.jnaerator.runtime.globals.GlobalPointerType;
import com.sun.jna.*;
import com.sun.jna.ptr.ByteByReference;

import java.nio.ByteBuffer;
import java.nio.IntBuffer;
import java.nio.ShortBuffer;

@SuppressWarnings({"unused", "SpellCheckingInspection"})

public interface CLibrary extends Library {
    public static final String JNA_LIBRARY_NAME = (com.sun.jna.Platform.isWindows() ? "msvcrt" : "c");
    public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(CLibrary.JNA_LIBRARY_NAME);
    public static final CLibrary INSTANCE = (CLibrary) Native.load(CLibrary.JNA_LIBRARY_NAME, CLibrary.class);

    public static interface __socket_type {
        public static final int SOCK_STREAM = 1;
        public static final int SOCK_DGRAM = 2;
        public static final int SOCK_RAW = 3;
        public static final int SOCK_RDM = 4;
        public static final int SOCK_SEQPACKET = 5;
        public static final int SOCK_DCCP = 6;
        public static final int SOCK_PACKET = 10;
        public static final int SOCK_CLOEXEC = 2000000;
        public static final int SOCK_NONBLOCK = 4000;
    }

    public static final int MSG_OOB = 0x01;
    public static final int MSG_PEEK = 0x02;
    public static final int MSG_DONTROUTE = 0x04;
    public static final int MSG_CTRUNC = 0x08;
    public static final int MSG_PROXY = 0x10;
    public static final int MSG_TRUNC = 0x20;
    public static final int MSG_DONTWAIT = 0x40;
    public static final int MSG_EOR = 0x80;
    public static final int MSG_WAITALL = 0x100;
    public static final int MSG_FIN = 0x200;
    public static final int MSG_SYN = 0x400;
    public static final int MSG_CONFIRM = 0x800;
    public static final int MSG_RST = 0x1000;
    public static final int MSG_ERRQUEUE = 0x2000;
    public static final int MSG_NOSIGNAL = 0x4000;
    public static final int MSG_MORE = 0x8000;
    public static final int MSG_WAITFORONE = 0x10000;
    public static final int MSG_CMSG_CLOEXEC = 0x40000000;
    public static final int SCM_RIGHTS = 0x01;
    public static final int SHUT_RD = 0;
    public static final int SHUT_WR = 1;
    public static final int SHUT_RDWR = 2;
    public static final int IFF_UP = 0x1;
    public static final int IFF_BROADCAST = 0x2;
    public static final int IFF_DEBUG = 0x4;
    public static final int IFF_LOOPBACK = 0x8;
    public static final int IFF_POINTOPOINT = 0x10;
    public static final int IFF_NOTRAILERS = 0x20;
    public static final int IFF_RUNNING = 0x40;
    public static final int IFF_NOARP = 0x80;
    public static final int IFF_PROMISC = 0x100;
    public static final int IFF_ALLMULTI = 0x200;
    public static final int IFF_MASTER = 0x400;
    public static final int IFF_SLAVE = 0x800;
    public static final int IFF_MULTICAST = 0x1000;
    public static final int IFF_PORTSEL = 0x2000;
    public static final int IFF_AUTOMEDIA = 0x4000;
    public static final int IFF_DYNAMIC = 0x8000;
    public static final int _PC_LINK_MAX = 0;
    public static final int _PC_MAX_CANON = 1;
    public static final int _PC_MAX_INPUT = 2;
    public static final int _PC_NAME_MAX = 3;
    public static final int _PC_PATH_MAX = 4;
    public static final int _PC_PIPE_BUF = 5;
    public static final int _PC_CHOWN_RESTRICTED = 6;
    public static final int _PC_NO_TRUNC = 7;
    public static final int _PC_VDISABLE = 8;
    public static final int _PC_SYNC_IO = 9;
    public static final int _PC_ASYNC_IO = 10;
    public static final int _PC_PRIO_IO = 11;
    public static final int _PC_SOCK_MAXBUF = 12;
    public static final int _PC_FILESIZEBITS = 13;
    public static final int _PC_REC_INCR_XFER_SIZE = 14;
    public static final int _PC_REC_MAX_XFER_SIZE = 15;
    public static final int _PC_REC_MIN_XFER_SIZE = 16;
    public static final int _PC_REC_XFER_ALIGN = 17;
    public static final int _PC_ALLOC_SIZE_MIN = 18;
    public static final int _PC_SYMLINK_MAX = 19;
    public static final int _PC_2_SYMLINKS = 20;
    public static final int _SC_ARG_MAX = 0;
    public static final int _SC_CHILD_MAX = 1;
    public static final int _SC_CLK_TCK = 2;
    public static final int _SC_NGROUPS_MAX = 3;
    public static final int _SC_OPEN_MAX = 4;
    public static final int _SC_STREAM_MAX = 5;
    public static final int _SC_TZNAME_MAX = 6;
    public static final int _SC_JOB_CONTROL = 7;
    public static final int _SC_SAVED_IDS = 8;
    public static final int _SC_REALTIME_SIGNALS = 9;
    public static final int _SC_PRIORITY_SCHEDULING = 10;
    public static final int _SC_TIMERS = 11;
    public static final int _SC_ASYNCHRONOUS_IO = 12;
    public static final int _SC_PRIORITIZED_IO = 13;
    public static final int _SC_SYNCHRONIZED_IO = 14;
    public static final int _SC_FSYNC = 15;
    public static final int _SC_MAPPED_FILES = 16;
    public static final int _SC_MEMLOCK = 17;
    public static final int _SC_MEMLOCK_RANGE = 18;
    public static final int _SC_MEMORY_PROTECTION = 19;
    public static final int _SC_MESSAGE_PASSING = 20;
    public static final int _SC_SEMAPHORES = 21;
    public static final int _SC_SHARED_MEMORY_OBJECTS = 22;
    public static final int _SC_AIO_LISTIO_MAX = 23;
    public static final int _SC_AIO_MAX = 24;
    public static final int _SC_AIO_PRIO_DELTA_MAX = 25;
    public static final int _SC_DELAYTIMER_MAX = 26;
    public static final int _SC_MQ_OPEN_MAX = 27;
    public static final int _SC_MQ_PRIO_MAX = 28;
    public static final int _SC_VERSION = 29;
    public static final int _SC_PAGESIZE = 30;
    public static final int _SC_RTSIG_MAX = 31;
    public static final int _SC_SEM_NSEMS_MAX = 32;
    public static final int _SC_SEM_VALUE_MAX = 33;
    public static final int _SC_SIGQUEUE_MAX = 34;
    public static final int _SC_TIMER_MAX = 35;
    public static final int _SC_BC_BASE_MAX = 36;
    public static final int _SC_BC_DIM_MAX = 37;
    public static final int _SC_BC_SCALE_MAX = 38;
    public static final int _SC_BC_STRING_MAX = 39;
    public static final int _SC_COLL_WEIGHTS_MAX = 40;
    public static final int _SC_EQUIV_CLASS_MAX = 41;
    public static final int _SC_EXPR_NEST_MAX = 42;
    public static final int _SC_LINE_MAX = 43;
    public static final int _SC_RE_DUP_MAX = 44;
    public static final int _SC_CHARCLASS_NAME_MAX = 45;
    public static final int _SC_2_VERSION = 46;
    public static final int _SC_2_C_BIND = 47;
    public static final int _SC_2_C_DEV = 48;
    public static final int _SC_2_FORT_DEV = 49;
    public static final int _SC_2_FORT_RUN = 50;
    public static final int _SC_2_SW_DEV = 51;
    public static final int _SC_2_LOCALEDEF = 52;
    public static final int _SC_PII = 53;
    public static final int _SC_PII_XTI = 54;
    public static final int _SC_PII_SOCKET = 55;
    public static final int _SC_PII_INTERNET = 56;
    public static final int _SC_PII_OSI = 57;
    public static final int _SC_POLL = 58;
    public static final int _SC_SELECT = 59;
    public static final int _SC_UIO_MAXIOV = 60;

    public static final int _CS_PATH = 0;
    public static final int _CS_V6_WIDTH_RESTRICTED_ENVS = 1;
    public static final int _CS_GNU_LIBC_VERSION = 2;
    public static final int _CS_GNU_LIBPTHREAD_VERSION = 3;
    public static final int _CS_V5_WIDTH_RESTRICTED_ENVS = 4;
    public static final int _CS_V7_WIDTH_RESTRICTED_ENVS = 5;
    public static final int _CS_LFS_CFLAGS = 1000;
    public static final int _CS_LFS_LDFLAGS = 1001;
    public static final int _CS_LFS_LIBS = 1002;
    public static final int _CS_LFS_LINTFLAGS = 1003;
    public static final int _CS_LFS64_CFLAGS = 1004;
    public static final int _CS_LFS64_LDFLAGS = 1005;
    public static final int _CS_LFS64_LIBS = 1006;
    public static final int _CS_LFS64_LINTFLAGS = 1007;
    public static final int _CS_XBS5_ILP32_OFF32_CFLAGS = 1100;
    public static final int _CS_XBS5_ILP32_OFF32_LDFLAGS = 1101;
    public static final int _CS_XBS5_ILP32_OFF32_LIBS = 1102;
    public static final int _CS_XBS5_ILP32_OFF32_LINTFLAGS = 1103;
    public static final int _CS_XBS5_ILP32_OFFBIG_CFLAGS = 1104;
    public static final int _CS_XBS5_ILP32_OFFBIG_LDFLAGS = 1105;
    public static final int _CS_XBS5_ILP32_OFFBIG_LIBS = 1106;
    public static final int _CS_XBS5_ILP32_OFFBIG_LINTFLAGS = 1107;
    public static final int _CS_XBS5_LP64_OFF64_CFLAGS = 1108;
    public static final int _CS_XBS5_LP64_OFF64_LDFLAGS = 1109;
    public static final int _CS_XBS5_LP64_OFF64_LIBS = 1110;
    public static final int _CS_XBS5_LP64_OFF64_LINTFLAGS = 1111;
    public static final int _CS_XBS5_LPBIG_OFFBIG_CFLAGS = 1112;
    public static final int _CS_XBS5_LPBIG_OFFBIG_LDFLAGS = 1113;
    public static final int _CS_XBS5_LPBIG_OFFBIG_LIBS = 1114;
    public static final int _CS_XBS5_LPBIG_OFFBIG_LINTFLAGS = 1115;
    public static final int _CS_POSIX_V6_ILP32_OFF32_CFLAGS = 1116;
    public static final int _CS_POSIX_V6_ILP32_OFF32_LDFLAGS = 1117;
    public static final int _CS_POSIX_V6_ILP32_OFF32_LIBS = 1118;
    public static final int _CS_POSIX_V6_ILP32_OFF32_LINTFLAGS = 1119;
    public static final int _CS_POSIX_V6_ILP32_OFFBIG_CFLAGS = 1120;
    public static final int _CS_POSIX_V6_ILP32_OFFBIG_LDFLAGS = 1121;
    public static final int _CS_POSIX_V6_ILP32_OFFBIG_LIBS = 1122;
    public static final int _CS_POSIX_V6_ILP32_OFFBIG_LINTFLAGS = 1123;
    public static final int _CS_POSIX_V6_LP64_OFF64_CFLAGS = 1124;
    public static final int _CS_POSIX_V6_LP64_OFF64_LDFLAGS = 1125;
    public static final int _CS_POSIX_V6_LP64_OFF64_LIBS = 1126;
    public static final int _CS_POSIX_V6_LP64_OFF64_LINTFLAGS = 1127;
    public static final int _CS_POSIX_V6_LPBIG_OFFBIG_CFLAGS = 1128;
    public static final int _CS_POSIX_V6_LPBIG_OFFBIG_LDFLAGS = 1129;
    public static final int _CS_POSIX_V6_LPBIG_OFFBIG_LIBS = 1130;
    public static final int _CS_POSIX_V6_LPBIG_OFFBIG_LINTFLAGS = 1131;
    public static final int _CS_POSIX_V7_ILP32_OFF32_CFLAGS = 1132;
    public static final int _CS_POSIX_V7_ILP32_OFF32_LDFLAGS = 1133;
    public static final int _CS_POSIX_V7_ILP32_OFF32_LIBS = 1134;
    public static final int _CS_POSIX_V7_ILP32_OFF32_LINTFLAGS = 1135;
    public static final int _CS_POSIX_V7_ILP32_OFFBIG_CFLAGS = 1136;
    public static final int _CS_POSIX_V7_ILP32_OFFBIG_LDFLAGS = 1137;
    public static final int _CS_POSIX_V7_ILP32_OFFBIG_LIBS = 1138;
    public static final int _CS_POSIX_V7_ILP32_OFFBIG_LINTFLAGS = 1139;
    public static final int _CS_POSIX_V7_LP64_OFF64_CFLAGS = 1140;
    public static final int _CS_POSIX_V7_LP64_OFF64_LDFLAGS = 1141;
    public static final int _CS_POSIX_V7_LP64_OFF64_LIBS = 1142;
    public static final int _CS_POSIX_V7_LP64_OFF64_LINTFLAGS = 1143;
    public static final int _CS_POSIX_V7_LPBIG_OFFBIG_CFLAGS = 1144;
    public static final int _CS_POSIX_V7_LPBIG_OFFBIG_LDFLAGS = 1145;
    public static final int _CS_POSIX_V7_LPBIG_OFFBIG_LIBS = 1146;
    public static final int _CS_POSIX_V7_LPBIG_OFFBIG_LINTFLAGS = 1147;
    public static final int _CS_V6_ENV = 1148;
    public static final int _CS_V7_ENV = 1149;
    public static final int CAN_RAW_FILTER = 1;
    public static final int CAN_RAW_ERR_FILTER = 2;
    public static final int CAN_RAW_LOOPBACK = 3;
    public static final int CAN_RAW_RECV_OWN_MSGS = 4;
    public static final int CGW_TYPE_UNSPEC = 0;
    public static final int CGW_TYPE_CAN_CAN = 1;
    public static final int __CGW_TYPE_MAX = 2;
    public static final int CGW_UNSPEC = 0;
    public static final int CGW_MOD_AND = 1;
    public static final int CGW_MOD_OR = 2;
    public static final int CGW_MOD_XOR = 3;
    public static final int CGW_MOD_SET = 4;
    public static final int CGW_CS_XOR = 5;
    public static final int CGW_CS_CRC8 = 6;
    public static final int CGW_HANDLED = 7;
    public static final int CGW_DROPPED = 8;
    public static final int CGW_SRC_IF = 9;
    public static final int CGW_DST_IF = 10;
    public static final int CGW_FILTER = 11;
    public static final int __CGW_MAX = 12;
    public static final int CGW_CRC8PRF_UNSPEC = 0;
    public static final int CGW_CRC8PRF_1U8 = 1;
    public static final int CGW_CRC8PRF_16U8 = 2;
    public static final int CGW_CRC8PRF_SFFID_XOR = 3;
    public static final int __CGW_CRC8PRF_MAX = 4;
    public static final int TX_SETUP = 1;
    public static final int TX_DELETE = 2;
    public static final int TX_READ = 3;
    public static final int TX_SEND = 4;
    public static final int RX_SETUP = 5;
    public static final int RX_DELETE = 6;
    public static final int RX_READ = 7;
    public static final int TX_STATUS = 8;
    public static final int TX_EXPIRED = 9;
    public static final int RX_STATUS = 10;
    public static final int RX_TIMEOUT = 11;
    public static final int RX_CHANGED = 12;

    public static interface can_state {
        public static final int CAN_STATE_ERROR_ACTIVE = 0;
        public static final int CAN_STATE_ERROR_WARNING = 1;
        public static final int CAN_STATE_ERROR_PASSIVE = 2;
        public static final int CAN_STATE_BUS_OFF = 3;
        public static final int CAN_STATE_STOPPED = 4;
        public static final int CAN_STATE_SLEEPING = 5;
        public static final int CAN_STATE_MAX = 6;
    }

    ;
    public static final int IFLA_CAN_UNSPEC = 0;
    public static final int IFLA_CAN_BITTIMING = 1;
    public static final int IFLA_CAN_BITTIMING_CONST = 2;
    public static final int IFLA_CAN_CLOCK = 3;
    public static final int IFLA_CAN_STATE = 4;
    public static final int IFLA_CAN_CTRLMODE = 5;
    public static final int IFLA_CAN_RESTART_MS = 6;
    public static final int IFLA_CAN_RESTART = 7;
    public static final int IFLA_CAN_BERR_COUNTER = 8;
    public static final int __IFLA_CAN_MAX = 9;
    public static final int SIOCSIFDSTADDR = (int) 0x8918;
    public static final int PF_TIPC = (int) 30;
    public static final int _LFS64_ASYNCHRONOUS_IO = (int) 1;
    public static final int TIOCPKT_DOSTOP = (int) 32;
    public static final int CAN_ERR_BUSOFF = (int) 0x00000040;
    public static final int CAN_EFF_FLAG = (int) 0x80000000;
    public static final int AF_FILE = (int) 1;
    public static final int F_LOCK = (int) 1;
    public static final int __SIZEOF_PTHREAD_MUTEX_T = (int) 40;
    public static final int TIOCGLCKTRMIOS = (int) 0x5456;
    public static final int F_TLOCK = (int) 2;
    public static final int SIOCDELDLCI = (int) 0x8981;
    public static final int _POSIX_SYNCHRONIZED_IO = (int) 200809;
    public static final int CMIN = (int) 1;
    public static final int CGW_FLAGS_CAN_ECHO = (int) 0x01;
    public static final int F_TEST = (int) 3;
    public static final int CLOCK_REALTIME_ALARM = (int) 8;
    public static final int __SIZEOF_PTHREAD_RWLOCKATTR_T = (int) 8;
    public static final int CAN_ERR_TRX_CANH_SHORT_TO_BAT = (int) 0x05;
    public static final int CAN_ISOTP = (int) 6;
    public static final int SEEK_END = (int) 2;
    public static final int CAN_CTRLMODE_ONE_SHOT = (int) 0x08;
    public static final int TCXONC = (int) 0x540A;
    public static final int SIOCGIFENCAP = (int) 0x8925;
    public static final int FIOASYNC = (int) 0x5452;
    public static final int CGW_MOD_FUNCS = (int) 4;
    public static final int __SIZEOF_PTHREAD_BARRIERATTR_T = (int) 4;
    public static final int CAN_ERR_PROT_STUFF = (int) 0x04;
    public static final int _POSIX_SPIN_LOCKS = (int) 200809;
    public static final int TIOCPKT_FLUSHWRITE = (int) 2;
    public static final int SIOCADDDLCI = (int) 0x8980;
    public static final int CLOCK_MONOTONIC = (int) 1;
    public static final int __PTHREAD_MUTEX_HAVE_PREV = (int) 1;
    public static final int N_PROFIBUS_FDL = (int) 10;
    public static final String __ILP32_OFFBIG_LDFLAGS = (String) "-m32";
    public static final int _LFS_LARGEFILE = (int) 1;
    public static final int SIOCSIFTXQLEN = (int) 0x8943;
    public static final int SOL_DECNET = (int) 261;
    public static final int _POSIX_REENTRANT_FUNCTIONS = (int) 1;
    public static final int __USE_XOPEN2K8 = (int) 1;
    public static final int TIOCGSOFTCAR = (int) 0x5419;
    public static final int __POSIX2_THIS_VERSION = (int) 200809;
    public static final int TIOCPKT_STOP = (int) 4;
    public static final int R_OK = (int) 4;
    public static final int PF_IEEE802154 = (int) 36;
    public static final int CLOCK_THREAD_CPUTIME_ID = (int) 3;
    public static final int TIOCSCTTY = (int) 0x540E;
    public static final int FIONCLEX = (int) 0x5450;
    public static final int TIOCPKT_DATA = (int) 0;
    public static final int IFNAMSIZ = (int) 16;
    public static final int IOCSIZE_SHIFT = (int) ((0 + 8) + 8);
    public static final int _XOPEN_ENH_I18N = (int) 1;
    public static final int PF_BLUETOOTH = (int) 31;
    public static final int L_SET = (int) 0;
    public static final int PF_PPPOX = (int) 24;
    public static final int SIOCRTMSG = (int) 0x890D;
    public static final int CAN_ERR_TRX_CANL_SHORT_TO_BAT = (int) 0x50;
    public static final int SIOCGIFSLAVE = (int) 0x8929;
    public static final int SIOCGIFCONF = (int) 0x8912;
    public static final int TIOCSERGETMULTI = (int) 0x545A;
    public static final int N_SLIP = (int) 1;
    public static final int AF_ROSE = (int) 11;
    public static final int SO_PASSCRED = (int) 16;
    public static final int TIOCCONS = (int) 0x541D;
    public static final int _BITS_PTHREADTYPES_H = (int) 1;
    public static final int CAN_ERR_PROT_LOC_CRC_DEL = (int) 0x18;
    public static final int __USE_BSD = (int) 1;
    public static final int CAN_ERR_ACK = (int) 0x00000020;
    public static final int _LFS64_STDIO = (int) 1;
    public static final int CLOCK_BOOTTIME = (int) 7;
    public static final int AF_LLC = (int) 26;
    public static final int SIOCSIFPFLAGS = (int) 0x8934;
    public static final int IOCSIZE_MASK = (int) (((1 << 14) - 1) << ((0 + 8) + 8));
    public static final int _XOPEN_REALTIME_THREADS = (int) 1;
    public static final int CAN_ERR_CRTL_RX_WARNING = (int) 0x04;
    public static final int _SYS_TYPES_H = (int) 1;
    public static final int CSUSP = (int) ('z' & 37);
    public static final int PDP_ENDIAN = (int) 3412;
    public static final int TCSBRK = (int) 0x5409;
    public static final int PF_MAX = (int) 40;
    public static final int _NET_IF_H = (int) 1;
    public static final int PF_AX25 = (int) 3;
    public static final int _POSIX_V6_LP64_OFF64 = (int) 1;
    public static final int SO_BSDCOMPAT = (int) 14;
    public static final int ITIMER_PROF = (int) 2;
    public static final int _SYS_SELECT_H = (int) 1;
    public static final int N_SMSBLOCK = (int) 12;
    public static final int SIOCSIFMTU = (int) 0x8922;
    public static final int CWERASE = (int) ('w' & 37);
    public static final int AF_SECURITY = (int) 14;
    public static final int PF_NETLINK = (int) 16;
    public static final int __BIT_TYPES_DEFINED__ = (int) 1;
    public static final int _IOC_NRMASK = (int) ((1 << 8) - 1);
    public static final int _POSIX_ASYNCHRONOUS_IO = (int) 200809;
    public static final int CAN_ERR_CRTL = (int) 0x00000004;
    public static final int TIOCEXCL = (int) 0x540C;
    public static final int PF_INET6 = (int) 10;
    public static final int PF_ASH = (int) 18;
    public static final int AF_IEEE802154 = (int) 36;
    public static final int CAN_NPROTO = (int) 7;
    public static final int CAN_ERR_PROT_LOC_INTERM = (int) 0x12;
    public static final int _BSD_SOURCE = (int) 1;
    public static final int CAN_ERR_PROT_LOC_ACK = (int) 0x19;
    public static final int RX_RTR_FRAME = (int) 0x0400;
    public static final int SIOCGIFMTU = (int) 0x8921;
    public static final int __USE_POSIX = (int) 1;
    public static final int SOL_AAL = (int) 265;
    public static final int __USE_SVID = (int) 1;
    public static final int _POSIX_TRACE_EVENT_FILTER = (int) -1;
    public static final int TIOCLINUX = (int) 0x541C;
    public static final int __LITTLE_ENDIAN = (int) 1234;
    public static final int __USE_ISOC99 = (int) 1;
    public static final int AF_UNSPEC = (int) 0;
    public static final int __USE_ISOC95 = (int) 1;
    public static final int SIOCSIFENCAP = (int) 0x8926;
    public static final int LITTLE_ENDIAN = (int) 1234;
    public static final int BIG_ENDIAN = (int) 4321;
    public static final int SO_KEEPALIVE = (int) 9;
    public static final int _POSIX_MESSAGE_PASSING = (int) 200809;
    public static final int UIO_MAXIOV = (int) 1024;
    public static final int IOC_INOUT = (int) ((1 | 2) << (((0 + 8) + 8) + 14));
    public static final int PF_NETROM = (int) 6;
    public static final int SO_SECURITY_ENCRYPTION_NETWORK = (int) 24;
    public static final int _UNISTD_H = (int) 1;
    public static final int CGW_MOD_DLC = (int) 0x02;
    public static final int CLNEXT = (int) ('v' & 37);
    public static final int RX_FILTER_ID = (int) 0x0020;
    public static final int TIOCSPGRP = (int) 0x5410;
    public static final int PF_APPLETALK = (int) 5;
    public static final int TIOCSBRK = (int) 0x5427;
    public static final int SCM_TIMESTAMPING = (int) 37;
    public static final int FD_SETSIZE = (int) 1024;
    public static final int _POSIX_PRIORITIZED_IO = (int) 200809;
    public static final int CAN_ERR_PROT_TX = (int) 0x80;
    public static final int CAN_ERR_CRTL_TX_PASSIVE = (int) 0x20;
    public static final int _POSIX_CHOWN_RESTRICTED = (int) 0;
    public static final int AF_NFC = (int) 39;
    public static final int SO_ERROR = (int) 4;
    public static final int STDERR_FILENO = (int) 2;
    public static final int X_OK = (int) 1;
    public static final int MAX_MODFUNCTIONS = (int) (4 * 3);
    public static final int _BITS_TYPESIZES_H = (int) 1;
    public static final int _POSIX2_LOCALEDEF = (int) 200809;
    public static final int _POSIX_TIMERS = (int) 200809;
    public static final int _IOC_READ = (int) 2;
    public static final int SIOCDEVPRIVATE = (int) 0x89F0;
    public static final int TIOCSRS485 = (int) 0x542F;
    public static final int SIOCGRARP = (int) 0x8961;
    public static final int __PDP_ENDIAN = (int) 3412;
    public static final int AF_WANPIPE = (int) 25;
    public static final int TIOCSSERIAL = (int) 0x541F;
    public static final int CAN_ERR_LOSTARB_UNSPEC = (int) 0x00;
    public static final int AF_LOCAL = (int) 1;
    public static final int SO_DONTROUTE = (int) 5;
    public static final int SIOCGIFDSTADDR = (int) 0x8917;
    public static final int CAN_SFF_MASK = (int) 0x000007FF;
    public static final int TIOCM_CAR = (int) 0x040;
    public static final int PF_PACKET = (int) 17;
    public static final int _POSIX_CPUTIME = (int) 0;
    public static final int TIOCMGET = (int) 0x5415;
    public static final int __WORDSIZE_COMPAT32 = (int) 1;
    public static final int CAN_ERR_CRTL_UNSPEC = (int) 0x00;
    public static final int CAN_ERR_PROT_LOC_ID20_18 = (int) 0x06;
    public static final int TIOCGSID = (int) 0x5429;
    public static final int _XOPEN_XPG2 = (int) 1;
    public static final int CAN_ERR_PROT_LOC_DLC = (int) 0x0B;
    public static final int CDISCARD = (int) ('o' & 37);
    public static final int SOL_SOCKET = (int) 1;
    public static final int _POSIX_JOB_CONTROL = (int) 1;
    public static final int CAN_ERR_CRTL_RX_OVERFLOW = (int) 0x01;
    public static final int _POSIX_THREAD_PRIO_INHERIT = (int) 200809;
    public static final int _BITS_UIO_H_FOR_SYS_UIO_H = (int) 1;
    public static final int _ENDIAN_H = (int) 1;
    public static final int _XOPEN_XPG4 = (int) 1;
    public static final int _XOPEN_XPG3 = (int) 1;
    public static final int CRPRNT = (int) ('r' & 37);
    public static final int __SIZEOF_PTHREAD_COND_T = (int) 48;
    public static final int __SIZEOF_PTHREAD_ATTR_T = (int) 56;
    public static final int FIONBIO = (int) 0x5421;
    public static final int SCM_TIMESTAMP = (int) 29;
    public static final int SCM_TIMESTAMPNS = (int) 35;
    public static final int CAN_ERR_PROT_BIT1 = (int) 0x10;
    public static final int CAN_ERR_PROT_BIT0 = (int) 0x08;
    public static final int __WORDSIZE = (int) 64;
    public static final int TIOCPKT_IOCTL = (int) 64;
    public static final String __LP64_OFF64_LDFLAGS = (String) "-m64";
    public static final int TIOCM_RNG = (int) 0x080;
    public static final int __USE_POSIX2 = (int) 1;
    public static final int CAN_EFF_MASK = (int) 0x1FFFFFFF;
    public static final int CAN_ERR_TRX_CANH_SHORT_TO_GND = (int) 0x07;
    public static final int SOL_IRDA = (int) 266;
    public static final int SOL_ATM = (int) 264;
    public static final int SO_PEERNAME = (int) 28;
    public static final int PF_FILE = (int) 1;
    public static final int SIOCGIFADDR = (int) 0x8915;
    public static final int PF_PHONET = (int) 35;
    public static final int AF_NETROM = (int) 6;
    public static final int SO_SECURITY_ENCRYPTION_TRANSPORT = (int) 23;
    public static final int IOC_IN = (int) (1 << (((0 + 8) + 8) + 14));
    public static final int TIOCM_RTS = (int) 0x004;
    public static final int SIOCGIFBR = (int) 0x8940;
    public static final int TIOCMBIS = (int) 0x5416;
    public static final int CAN_ERR_PROT_LOC_ID28_21 = (int) 0x02;
    public static final int __SIZEOF_PTHREAD_RWLOCK_T = (int) 56;
    public static final int PF_LLC = (int) 26;
    public static final int CLOCK_REALTIME = (int) 0;
    public static final int _POSIX_MEMORY_PROTECTION = (int) 200809;
    public static final int CAN_ERR_BUSERROR = (int) 0x00000080;
    public static final int _XOPEN_SHM = (int) 1;
    public static final int PF_RDS = (int) 21;
    public static final int _POSIX_SPAWN = (int) 200809;
    public static final int RX_NO_AUTOTIMER = (int) 0x0080;
    public static final int CAN_ERR_PROT_UNSPEC = (int) 0x00;
    public static final int __USE_POSIX_IMPLICITLY = (int) 1;
    public static final int N_R3964 = (int) 9;
    public static final int AF_ECONET = (int) 19;
    public static final int __SIZEOF_PTHREAD_MUTEXATTR_T = (int) 4;
    public static final int SIOCGIFFLAGS = (int) 0x8913;
    public static final int CAN_CTRLMODE_3_SAMPLES = (int) 0x04;
    public static final int PF_LOCAL = (int) 1;
    public static final int __USE_MISC = (int) 1;
    public static final int _POSIX_SEMAPHORES = (int) 200809;
    public static final int CAN_INV_FILTER = (int) 0x20000000;
    public static final int SIOCSIFLINK = (int) 0x8911;
    public static final int __SIZEOF_PTHREAD_BARRIER_T = (int) 32;
    public static final int __USE_ANSI = (int) 1;
    public static final int N_PPP = (int) 3;
    public static final int _XOPEN_UNIX = (int) 1;
    public static final int TIOCMSET = (int) 0x5418;
    public static final int SO_TIMESTAMPNS = (int) 35;
    public static final int PF_BRIDGE = (int) 7;
    public static final int SOL_PACKET = (int) 263;
    public static final int _IOC_SIZEBITS = (int) 14;
    public static final int _POSIX_THREAD_ATTR_STACKSIZE = (int) 200809;
    public static final int CAN_ERR_CRTL_RX_PASSIVE = (int) 0x10;
    public static final int CAN_ERR_PROT_LOC_ACK_DEL = (int) 0x1B;
    public static final int _POSIX_REALTIME_SIGNALS = (int) 200809;
    public static final int AF_IRDA = (int) 23;
    public static final int _POSIX_THREAD_SPORADIC_SERVER = (int) -1;
    public static final int TIOCVHANGUP = (int) 0x5437;
    public static final int SO_PRIORITY = (int) 12;
    public static final int CAN_ERR_PROT_LOC_RTR = (int) 0x0C;
    public static final int TCSETXW = (int) 0x5435;
    public static final int _POSIX_THREAD_PRIO_PROTECT = (int) 200809;
    public static final int _SYS_SOCKET_H = (int) 1;
    public static final int TCSETXF = (int) 0x5434;
    public static final int PF_ROUTE = (int) 16;
    public static final int TIOCM_DSR = (int) 0x100;
    public static final int _IOC_TYPEBITS = (int) 8;
    public static final int _POSIX_MEMLOCK_RANGE = (int) 200809;
    public static final int CAN_ERR_TRX_CANL_SHORT_TO_CANH = (int) 0x80;
    public static final int AF_KEY = (int) 15;
    public static final int _POSIX_MEMLOCK = (int) 200809;
    public static final int _POSIX_ADVISORY_INFO = (int) 200809;
    public static final int _POSIX_SAVED_IDS = (int) 1;
    public static final int SO_LINGER = (int) 13;
    public static final int _POSIX_MONOTONIC_CLOCK = (int) 0;
    public static final int AF_PPPOX = (int) 24;
    public static final int SO_RXQ_OVFL = (int) 40;
    public static final int CAN_ERR_PROT_OVERLOAD = (int) 0x20;
    public static final int _POSIX_SOURCE = (int) 1;
    public static final int TIOCM_DTR = (int) 0x002;
    public static final int TIOCNXCL = (int) 0x540D;
    public static final int SIOCGIFINDEX = (int) 0x8933;
    public static final int N_TTY = (int) 0;
    public static final int SIOCGIFPFLAGS = (int) 0x8935;
    public static final int PF_ROSE = (int) 11;
    public static final int AF_RDS = (int) 21;
    public static final int TCSETSW = (int) 0x5403;
    public static final int SOL_CAN_BASE = (int) 100;
    public static final int CAN_ERR_PROT_LOC_DATA = (int) 0x0A;
    public static final int SIOCSARP = (int) 0x8955;
    public static final int TIOCSTI = (int) 0x5412;
    public static final int TIOCPKT_START = (int) 8;
    public static final int CLOCK_MONOTONIC_COARSE = (int) 6;
    public static final int N_HDLC = (int) 13;
    public static final int TIOCMIWAIT = (int) 0x545C;
    public static final int TCSETSF = (int) 0x5404;
    public static final int _POSIX_ASYNC_IO = (int) 1;
    public static final int __STDC_IEC_559_COMPLEX__ = (int) 1;
    public static final int SIOCSIFBR = (int) 0x8941;
    public static final int CLOCK_SGI_CYCLE = (int) 10;
    public static final int STDIN_FILENO = (int) 0;
    public static final int CLOCK_BOOTTIME_ALARM = (int) 9;
    public static final int _POSIX_NO_TRUNC = (int) 1;
    public static final int SO_ACCEPTCONN = (int) 30;
    public static final int CGW_MOD_ID = (int) 0x01;
    public static final int SIOCGIFHWADDR = (int) 0x8927;
    public static final int _LFS64_LARGEFILE = (int) 1;
    public static final int FIOGETOWN = (int) 0x8903;
    public static final int CAN_RAW = (int) 1;
    public static final int AF_ATMSVC = (int) 20;
    public static final int _BITS_UIO_H = (int) 1;
    public static final int _XOPEN_VERSION = (int) 700;
    public static final int _ATFILE_SOURCE = (int) 1;
    public static final int _SS_SIZE = (int) 128;
    public static final int SIOCGARP = (int) 0x8954;
    public static final int CLOCK_REALTIME_COARSE = (int) 5;
    public static final int SIOCSIFADDR = (int) 0x8916;
    public static final int SO_PASSSEC = (int) 34;
    public static final int _POSIX_THREAD_ATTR_STACKADDR = (int) 200809;
    public static final int IF_NAMESIZE = (int) 16;
    public static final int TIOCSWINSZ = (int) 0x5414;
    public static final int SO_DEBUG = (int) 1;
    public static final int CSTOP = (int) ('s' & 37);
    public static final int TCSETAW = (int) 0x5407;
    public static final int SO_PEERCRED = (int) 17;
    public static final int _POSIX_TIMEOUTS = (int) 200809;
    public static final int SIOCDELRT = (int) 0x890C;
    public static final int _POSIX_RAW_SOCKETS = (int) 200809;
    public static final int SO_RCVBUF = (int) 8;
    public static final int SIOCSRARP = (int) 0x8962;
    public static final int CAN_ERR_PROT_LOC_CRC_SEQ = (int) 0x08;
    public static final int AF_ALG = (int) 38;
    public static final int SIOCSIFHWADDR = (int) 0x8924;
    public static final int CAN_ERR_PROT_LOC_RES0 = (int) 0x09;
    public static final int CAN_ERR_PROT_LOC_RES1 = (int) 0x0D;
    public static final int __GLIBC_HAVE_LONG_LONG = (int) 1;
    public static final String __ILP32_OFFBIG_CFLAGS = (String) "-m32 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64";
    public static final int FIOQSIZE = (int) 0x5460;
    public static final int __BYTE_ORDER = (int) 1234;
    public static final int _XBS5_LPBIG_OFFBIG = (int) -1;
    public static final int TCSETAF = (int) 0x5408;
    public static final int PF_RXRPC = (int) 33;
    public static final int SEEK_SET = (int) 0;
    public static final int AF_BLUETOOTH = (int) 31;
    public static final int SO_RCVBUFFORCE = (int) 33;
    public static final int PF_CAIF = (int) 37;
    public static final int CAN_ERR_PROT_LOC_UNSPEC = (int) 0x00;
    public static final int _POSIX_PRIORITY_SCHEDULING = (int) 200809;
    public static final int MAX_CLOCKS = (int) 16;
    public static final int PF_ISDN = (int) 34;
    public static final int PF_IUCV = (int) 32;
    public static final int AF_X25 = (int) 9;
    public static final int _XBS5_LP64_OFF64 = (int) 1;
    public static final int CGW_FLAGS_CAN_SRC_TSTAMP = (int) 0x02;
    public static final int SO_SECURITY_AUTHENTICATION = (int) 22;
    public static final int SO_RCVTIMEO = (int) 20;
    public static final int N_6PACK = (int) 7;
    public static final int __STDC_IEC_559__ = (int) 1;
    public static final int CAN_ERR_LOSTARB = (int) 0x00000002;
    public static final int SIOCGIFMETRIC = (int) 0x891d;
    public static final int N_AX25 = (int) 5;
    public static final int __GLIBC__ = (int) 2;
    public static final int __USE_FORTIFY_LEVEL = (int) 0;
    public static final int CFLUSH = (int) ('o' & 37);
    public static final int _IOC_DIRBITS = (int) 2;
    public static final int AF_SNA = (int) 22;
    public static final int _POSIX_THREAD_ROBUST_PRIO_INHERIT = (int) 200809;
    public static final int SO_NO_CHECK = (int) 11;
    public static final int _POSIX_V7_LPBIG_OFFBIG = (int) -1;
    public static final int AF_DECnet = (int) 12;
    public static final int ITIMER_VIRTUAL = (int) 1;
    public static final int CAN_RTR_FLAG = (int) 0x40000000;
    public static final int CAN_ERR_TRX_CANH_NO_WIRE = (int) 0x04;
    public static final int __USE_POSIX199309 = (int) 1;
    public static final int SO_BROADCAST = (int) 6;
    public static final int SIOCDIFADDR = (int) 0x8936;
    public static final int CAN_CTRLMODE_LOOPBACK = (int) 0x01;
    public static final int SO_SNDBUF = (int) 7;
    public static final int F_OK = (int) 0;
    public static final int N_IRDA = (int) 11;
    public static final int _XOPEN_LEGACY = (int) 1;
    public static final int SIOCATMARK = (int) 0x8905;
    public static final int STARTTIMER = (int) 0x0002;
    public static final int CAN_ERR_PROT_BIT = (int) 0x01;
    public static final int N_HCI = (int) 15;
    public static final int _XOPEN_REALTIME = (int) 1;
    public static final int SIOCGIFNETMASK = (int) 0x891b;
    public static final int __GNU_LIBRARY__ = (int) 6;
    public static final int CAN_ERR_PROT_ACTIVE = (int) 0x40;
    public static final int _BITS_BYTESWAP_H = (int) 1;
    public static final int _IOC_NRSHIFT = (int) 0;
    public static final int SIOCADDRT = (int) 0x890B;
    public static final int AF_IPX = (int) 4;
    public static final int CAN_ERR_DLC = (int) 8;
    public static final int CDSUSP = (int) ('y' & 37);
    public static final int IOC_OUT = (int) (2 << (((0 + 8) + 8) + 14));
    public static final int SIOCSIFMAP = (int) 0x8971;
    public static final int SIOCDRARP = (int) 0x8960;
    public static final int SETTIMER = (int) 0x0001;
    public static final int TCSETA = (int) 0x5406;
    public static final int CLOCK_PROCESS_CPUTIME_ID = (int) 2;
    public static final int CGW_MOD_DATA = (int) 0x04;
    public static final int _IOC_DIRMASK = (int) ((1 << 2) - 1);
    public static final int CAN_BCM = (int) 2;
    public static final int SIOCGSTAMP = (int) 0x8906;
    public static final int N_SYNC_PPP = (int) 14;
    public static final int _SVID_SOURCE = (int) 1;
    public static final int FIONREAD = (int) 0x541B;
    public static final int AF_UNIX = (int) 1;
    public static final int TIOCM_ST = (int) 0x008;
    public static final int TIOCM_SR = (int) 0x010;
    public static final int SO_MARK = (int) 36;
    public static final String __ILP32_OFF32_LDFLAGS = (String) "-m32";
    public static final int AF_MAX = (int) 40;
    public static final int _POSIX_TRACE_INHERIT = (int) -1;
    public static final int _SYS_IOCTL_H = (int) 1;
    public static final int SO_TYPE = (int) 3;
    public static final int AF_CAN = (int) 29;
    public static final int TCGETA = (int) 0x5405;
    public static final int SOMAXCONN = (int) 128;
    public static final int SO_RCVLOWAT = (int) 18;
    public static final int SIOCPROTOPRIVATE = (int) 0x89E0;
    public static final int TCGETS = (int) 0x5401;
    public static final int NULL = (int) 0;
    public static final int SO_REUSEADDR = (int) 2;
    public static final int CAN_ERR_TRX_CANH_SHORT_TO_VCC = (int) 0x06;
    public static final int FIOCLEX = (int) 0x5451;
    public static final int TCGETX = (int) 0x5432;
    public static final int SIOCGIFNAME = (int) 0x8910;
    public static final int SIOCDARP = (int) 0x8953;
    public static final int TCSBRKP = (int) 0x5425;
    public static final int AF_ASH = (int) 18;
    public static final int CLOCK_MONOTONIC_RAW = (int) 4;
    public static final int PF_NFC = (int) 39;
    public static final int SO_SNDBUFFORCE = (int) 32;
    public static final int TCSETS = (int) 0x5402;
    public static final int TIMER_ABSTIME = (int) 0x01;
    public static final int TCSETX = (int) 0x5433;
    public static final int SO_ATTACH_FILTER = (int) 26;
    public static final int _POSIX_SHARED_MEMORY_OBJECTS = (int) 200809;
    public static final int SO_SNDTIMEO = (int) 21;
    public static final int CAN_CTRLMODE_LISTENONLY = (int) 0x02;
    public static final int TIOCNOTTY = (int) 0x5422;
    public static final int _POSIX_SHELL = (int) 1;
    public static final int CAN_ERR_TRX_CANL_SHORT_TO_GND = (int) 0x70;
    public static final int CAN_ERR_PROT_LOC_IDE = (int) 0x05;
    public static final int N_MOUSE = (int) 2;
    public static final int CAN_ERR_PROT_LOC_ID17_13 = (int) 0x07;
    public static final int PF_NETBEUI = (int) 13;
    public static final int _IOC_DIRSHIFT = (int) (((0 + 8) + 8) + 14);
    public static final int SIOCSIFFLAGS = (int) 0x8914;
    public static final int __STDC_ISO_10646__ = (int) 200009;
    public static final int __SIZEOF_PTHREAD_CONDATTR_T = (int) 4;
    public static final int TX_COUNTEVT = (int) 0x0004;
    public static final int AF_ATMPVC = (int) 8;
    public static final int CERASE = (int) 177;
    public static final int PF_WANPIPE = (int) 25;
    public static final int SOL_RAW = (int) 255;
    public static final int TIOCPKT_NOSTOP = (int) 16;
    public static final int _XOPEN_XCU_VERSION = (int) 4;
    public static final int SIOGIFINDEX = (int) 0x8933;
    public static final int _IOC_SIZEMASK = (int) ((1 << 14) - 1);
    public static final int PF_CAN = (int) 29;
    public static final int TIOCCBRK = (int) 0x5428;
    public static final int NCC = (int) 8;
    public static final int SO_TIMESTAMPING = (int) 37;
    public static final int _POSIX_CLOCK_SELECTION = (int) 200809;
    public static final int _POSIX_IPV6 = (int) 200809;
    public static final int _POSIX2_C_DEV = (int) 200809;
    public static final int N_STRIP = (int) 4;
    public static final int SIOCGIFCOUNT = (int) 0x8938;
    public static final int PF_IPX = (int) 4;
    public static final int AF_RXRPC = (int) 33;
    public static final int SIOCGIFTXQLEN = (int) 0x8942;
    public static final int TCFLSH = (int) 0x540B;
    public static final int _BITS_TYPES_H = (int) 1;
    public static final char _POSIX_VDISABLE = (char) '\0';
    public static final int SIOCSIFMETRIC = (int) 0x891e;
    public static final int PF_ECONET = (int) 19;
    public static final int PF_ATMPVC = (int) 8;
    public static final int _POSIX_REGEXP = (int) 1;
    public static final int __FD_SETSIZE = (int) 1024;
    public static final int ITIMER_REAL = (int) 0;
    public static final int _POSIX2_SW_DEV = (int) 200809;
    public static final int SEEK_CUR = (int) 1;
    public static final int TIOCGSERIAL = (int) 0x541E;
    public static final int TIOCGWINSZ = (int) 0x5413;
    public static final int AF_NETLINK = (int) 16;
    public static final int CAN_ERR_TX_TIMEOUT = (int) 0x00000001;
    public static final int TIOCSER_TEMT = (int) 0x01;
    public static final int PF_INET = (int) 2;
    public static final int _POSIX_C_SOURCE = (int) 200809;
    public static final int STDOUT_FILENO = (int) 1;
    public static final int AF_INET6 = (int) 10;
    public static final int _IOC_NONE = (int) 0;
    public static final int PF_ATMSVC = (int) 20;
    public static final int TIOCM_LE = (int) 0x001;
    public static final int __USE_XOPEN2K = (int) 1;
    public static final int AF_ROUTE = (int) 16;
    public static final int TIOCPKT_FLUSHREAD = (int) 1;
    public static final int _LFS_ASYNCHRONOUS_IO = (int) 1;
    public static final int CAN_ERR_MASK = (int) 0x1FFFFFFF;
    public static final int __GLIBC_MINOR__ = (int) 15;
    public static final int _IOC_TYPEMASK = (int) ((1 << 8) - 1);
    public static final int F_ULOCK = (int) 0;
    public static final int PF_UNSPEC = (int) 0;
    public static final int TIOCOUTQ = (int) 0x5411;
    public static final int SIOCSPGRP = (int) 0x8902;
    public static final int CAN_CTRLMODE_BERR_REPORTING = (int) 0x10;
    public static final int CAN_ERR_PROT_LOC_EOF = (int) 0x1A;
    public static final int _SYS_UIO_H = (int) 1;
    public static final int W_OK = (int) 2;
    public static final char CSTATUS = (char) '\0';
    public static final int _POSIX_TRACE_LOG = (int) -1;
    public static final int CAN_ERR_PROT = (int) 0x00000008;
    public static final int N_MASC = (int) 8;
    public static final int CLOCKS_MASK = (int) (0 | 1);
    public static final int _IOC_SIZESHIFT = (int) ((0 + 8) + 8);
    public static final int _POSIX_V6_LPBIG_OFFBIG = (int) -1;
    public static final int SIOCGSTAMPNS = (int) 0x8907;
    public static final int CAN_ERR_TRX_CANL_SHORT_TO_VCC = (int) 0x60;
    public static final int _POSIX2_C_BIND = (int) 200809;
    public static final int TIOCSERSETMULTI = (int) 0x545B;
    public static final int AF_PACKET = (int) 17;
    public static final int TX_CP_CAN_ID = (int) 0x0010;
    public static final int _FEATURES_H = (int) 1;
    public static final int CAN_ERR_PROT_LOC_SOF = (int) 0x03;
    public static final int AF_CAIF = (int) 37;
    public static final int CLOCKS_MONO = (int) 1;
    public static final int SO_PEERSEC = (int) 31;
    public static final int PF_ALG = (int) 38;
    public static final int PF_KEY = (int) 15;
    public static final int CREPRINT = (int) ('r' & 37);
    public static final int __USE_ATFILE = (int) 1;
    public static final int SOL_X25 = (int) 262;
    public static final int _STRUCT_TIMEVAL = (int) 1;
    public static final int TIOCSLCKTRMIOS = (int) 0x5457;
    public static final int CAN_ERR_TRX_CANL_NO_WIRE = (int) 0x40;
    public static final int TIOCGPGRP = (int) 0x540F;
    public static final int RX_CHECK_DLC = (int) 0x0040;
    public static final int CTIME = (int) 0;
    public static final int _POSIX2_VERSION = (int) 200809;
    public static final int AF_AX25 = (int) 3;
    public static final int _POSIX_FSYNC = (int) 200809;
    public static final int SIOCSIFNAME = (int) 0x8923;
    public static final int __BIG_ENDIAN = (int) 4321;
    public static final int _BITS_SOCKADDR_H = (int) 1;
    public static final int PF_UNIX = (int) 1;
    public static final int PF_DECnet = (int) 12;
    public static final int _POSIX2_CHAR_TERM = (int) 200809;
    public static final int SO_OOBINLINE = (int) 10;
    public static final int _XOPEN_CRYPT = (int) 1;
    public static final int SO_DOMAIN = (int) 39;
    public static final int SOL_CAN_RAW = (int) (100 + 1);
    public static final int AF_NETBEUI = (int) 13;
    public static final char CBRK = (char) '\0';
    public static final int __USE_POSIX199506 = (int) 1;
    public static final int CAN_ERR_PROT_LOC_SRTR = (int) 0x04;
    public static final int CINTR = (int) ('c' & 37);
    public static final int SO_DETACH_FILTER = (int) 27;
    public static final String __LP64_OFF64_CFLAGS = (String) "-m64";
    public static final int _POSIX_VERSION = (int) 200809;
    public static final int CSTART = (int) ('q' & 37);
    public static final int TIOCM_RI = (int) 0x080;
    public static final int TX_ANNOUNCE = (int) 0x0008;
    public static final int TIOCGICOUNT = (int) 0x545D;
    public static final int _POSIX_SPORADIC_SERVER = (int) -1;
    public static final int _IOC_NRBITS = (int) 8;
    public static final int CAN_ERR_CRTL_TX_OVERFLOW = (int) 0x02;
    public static final int TIOCMBIC = (int) 0x5417;
    public static final int SIOCSIFSLAVE = (int) 0x8930;
    public static final int CGW_FRAME_MODS = (int) 3;
    public static final int _POSIX_THREADS = (int) 200809;
    public static final int BYTE_ORDER = (int) 1234;
    public static final int CAN_MCNET = (int) 5;
    public static final int _POSIX_THREAD_SAFE_FUNCTIONS = (int) 200809;
    public static final int CAN_ERR_FLAG = (int) 0x20000000;
    public static final int TIOCSERGSTRUCT = (int) 0x5458;
    public static final int SIOCGIFMEM = (int) 0x891f;
    public static final int _POSIX_MAPPED_FILES = (int) 200809;
    public static final int SIOCADDMULTI = (int) 0x8931;
    public static final int SIOCGPGRP = (int) 0x8904;
    public static final int AF_ISDN = (int) 34;
    public static final int SIOCDELMULTI = (int) 0x8932;
    public static final int TIOCPKT = (int) 0x5420;
    public static final int AF_PHONET = (int) 35;
    public static final int _POSIX_THREAD_CPUTIME = (int) 0;
    public static final int TX_RESET_MULTI_IDX = (int) 0x0200;
    public static final int TIOCGETD = (int) 0x5424;
    public static final int N_X25 = (int) 6;
    public static final int AF_INET = (int) 2;
    public static final int TIOCSERSWILD = (int) 0x5455;
    public static final int CAN_ERR_TRX = (int) 0x00000010;
    public static final int L_INCR = (int) 1;
    public static final int AF_BRIDGE = (int) 7;
    public static final int SO_BINDTODEVICE = (int) 25;
    public static final int CEOT = (int) ('d' & 37);
    public static final int TIOCM_CD = (int) 0x040;
    public static final int _POSIX_BARRIERS = (int) 200809;
    public static final char CEOL = (char) '\0';
    public static final int CEOF = (int) ('d' & 37);
    public static final int TIOCSERGWILD = (int) 0x5454;
    public static final int _SIGSET_H_types = (int) 1;
    public static final int SIOCSIFHWBROADCAST = (int) 0x8937;
    public static final int SIOCSIFMEM = (int) 0x8920;
    public static final int SO_SNDLOWAT = (int) 19;
    public static final int CAN_ERR_PROT_LOC_ID04_00 = (int) 0x0E;
    public static final int CAN_ERR_CRTL_TX_WARNING = (int) 0x08;
    public static final int CAN_ERR_RESTARTED = (int) 0x00000100;
    public static final int TIOCSERGETLSR = (int) 0x5459;
    public static final int SO_TIMESTAMP = (int) 29;
    public static final int FIOSETOWN = (int) 0x8901;
    public static final int _POSIX_THREAD_PROCESS_SHARED = (int) 200809;
    public static final int _POSIX_THREAD_PRIORITY_SCHEDULING = (int) 200809;
    public static final int PF_SNA = (int) 22;
    public static final int _POSIX_TRACE = (int) -1;
    public static final int CQUIT = (int) 34;
    public static final String __ILP32_OFF32_CFLAGS = (String) "-m32";
    public static final int _IOC_WRITE = (int) 1;
    public static final int _K_SS_MAXSIZE = (int) 128;
    public static final int CKILL = (int) ('u' & 37);
    public static final int CAN_ERR_PROT_LOC_ID12_05 = (int) 0x0F;
    public static final int __FLOAT_WORD_ORDER = (int) 1234;
    public static final int _SYS_SYSMACROS_H = (int) 1;
    public static final int _SYS_CDEFS_H = (int) 1;
    public static final int IFHWADDRLEN = (int) 6;
    public static final int TIOCSERCONFIG = (int) 0x5453;
    public static final int _POSIX_THREAD_ROBUST_PRIO_PROTECT = (int) -1;
    public static final int _IOC_TYPESHIFT = (int) (0 + 8);
    public static final int AF_APPLETALK = (int) 5;
    public static final int _BITS_POSIX_OPT_H = (int) 1;
    public static final int TIOCSETD = (int) 0x5423;
    public static final int _POSIX_V7_LP64_OFF64 = (int) 1;
    public static final int _POSIX_TYPED_MEMORY_OBJECTS = (int) -1;
    public static final int PF_IRDA = (int) 23;
    public static final int _POSIX_READER_WRITER_LOCKS = (int) 200809;
    public static final int RX_ANNOUNCE_RESUME = (int) 0x0100;
    public static final int SIOCSIFBRDADDR = (int) 0x891a;
    public static final int SIOCGIFBRDADDR = (int) 0x8919;
    public static final int TIOCGRS485 = (int) 0x542E;
    public static final int PF_SECURITY = (int) 14;
    public static final int AF_IUCV = (int) 32;
    public static final int CAN_TP16 = (int) 3;
    public static final int SIOCSIFNETMASK = (int) 0x891c;
    public static final int TIOCSSOFTCAR = (int) 0x541A;
    public static final int CAN_ERR_TRX_UNSPEC = (int) 0x00;
    public static final int L_XTND = (int) 2;
    public static final int TIOCINQ = (int) 0x541B;
    public static final int AF_TIPC = (int) 30;
    public static final int PF_X25 = (int) 9;
    public static final int TIOCM_CTS = (int) 0x020;
    public static final int CAN_ERR_PROT_FORM = (int) 0x02;
    public static final int SIOCGIFMAP = (int) 0x8970;
    public static final int CAN_TP20 = (int) 4;
    public static final int SO_PROTOCOL = (int) 38;

    public interface __kernel_sighandler_t extends Callback {
        void apply(int int1);
    }

    ;

    int gnu_dev_major(NativeLong __dev);

    int gnu_dev_minor(NativeLong __dev);

    NativeLong gnu_dev_makedev(int __major, int __minor);

    NativeLong process_vm_readv(int __pid, iovec __lvec, NativeLong __liovcnt, iovec __rvec, NativeLong __riovcnt, NativeLong __flags);

    NativeLong process_vm_writev(int __pid, iovec __lvec, NativeLong __liovcnt, iovec __rvec, NativeLong __riovcnt, NativeLong __flags);

    NativeLong readv(int __fd, iovec __iovec, int __count);

    NativeLong writev(int __fd, iovec __iovec, int __count);

    NativeLong preadv(int __fd, iovec __iovec, int __count, NativeLong __offset);

    NativeLong pwritev(int __fd, iovec __iovec, int __count, NativeLong __offset);

    cmsghdr __cmsg_nxthdr(msghdr __mhdr, cmsghdr __cmsg);

    int recvmmsg(int __fd, mmsghdr __vmessages, int __vlen, int __flags, TimeSpec __tmo);

    int sendmmsg(int __fd, mmsghdr __vmessages, int __vlen, int __flags);

    int socket(int __domain, int __type, int __protocol);

    int socketpair(int __domain, int __type, int __protocol, IntBuffer __fds);

    int bind(int __fd, sockaddr __addr, int __len);

    int getsockname(int __fd, sockaddr __addr, IntBuffer __len);

    int connect(int __fd, sockaddr __addr, int __len);

    int getpeername(int __fd, sockaddr __addr, IntBuffer __len);

    NativeLong send(int __fd, Pointer __buf, NativeSize __n, int __flags);

    NativeLong recv(int __fd, Pointer __buf, NativeSize __n, int __flags);

    NativeLong sendto(int __fd, Pointer __buf, NativeSize __n, int __flags, sockaddr __addr, int __addr_len);

    NativeLong recvfrom(int __fd, Pointer __buf, NativeSize __n, int __flags, sockaddr __addr, IntBuffer __addr_len);

    NativeLong sendmsg(int __fd, msghdr __message, int __flags);

    NativeLong recvmsg(int __fd, msghdr __message, int __flags);

    int getsockopt(int __fd, int __level, int __optname, Pointer __optval, IntBuffer __optlen);

    int setsockopt(int __fd, int __level, int __optname, Pointer __optval, int __optlen);

    int listen(int __fd, int __n);

    int accept(int __fd, sockaddr __addr, IntBuffer __addr_len);

    int shutdown(int __fd, int __how);

    int sockatmark(int __fd);

    int isfdtype(int __fd, int __fdtype);

    int if_nametoindex(String __ifname);

    Pointer if_indextoname(int __ifindex, ByteBuffer __ifname);

    if_nameindex if_nameindex();

    void if_freenameindex(if_nameindex __ptr);

    int access(String __name, int __type);

    int faccessat(int __fd, String __file, int __type, int __flag);

    NativeLong lseek(int __fd, NativeLong __offset, int __whence);

    int close(int __fd);

    NativeLong read(int __fd, Pointer __buf, NativeSize __nbytes);

    NativeLong write(int __fd, Pointer __buf, NativeSize __n);

    NativeLong pread(int __fd, Pointer __buf, NativeSize __nbytes, NativeLong __offset);

    NativeLong pwrite(int __fd, Pointer __buf, NativeSize __n, NativeLong __offset);

    int pipe(IntBuffer __pipedes);

    int alarm(int __seconds);

    int sleep(int __seconds);

    int ualarm(int __value, int __interval);

    int usleep(int __useconds);

    int pause();

    int chown(String __file, int __owner, int __group);

    int fchown(int __fd, int __owner, int __group);

    int lchown(String __file, int __owner, int __group);

    int fchownat(int __fd, String __file, int __owner, int __group, int __flag);

    int chdir(String __path);

    int fchdir(int __fd);

    Pointer getcwd(ByteBuffer __buf, NativeSize __size);

    Pointer getwd(ByteBuffer __buf);

    int dup(int __fd);

    int dup2(int __fd, int __fd2);

    int execve(String __path, String __argv[], String __envp[]);

    int fexecve(int __fd, String __argv[], String __envp[]);

    int execv(String __path, String __argv[]);

    int execle(String __path, String __arg, Object... varargs);

    int execl(String __path, String __arg, Object... varargs);

    int execvp(String __file, String __argv[]);

    int execlp(String __file, String __arg, Object... varargs);

    int nice(int __inc);

    void _exit(int __status);

    NativeLong pathconf(String __path, int __name);

    NativeLong fpathconf(int __fd, int __name);

    NativeLong sysconf(int __name);

    NativeSize confstr(int __name, ByteBuffer __buf, NativeSize __len);

    int getpid();

    int getppid();

    int getpgrp();

    int __getpgid(int __pid);

    int getpgid(int __pid);

    int setpgid(int __pid, int __pgid);

    int setpgrp();

    int setsid();

    int getsid(int __pid);

    int getuid();

    int geteuid();

    int getgid();

    int getegid();

    int getgroups(int __size, IntBuffer __list);

    int setuid(int __uid);

    int setreuid(int __ruid, int __euid);

    int seteuid(int __uid);

    int setgid(int __gid);

    int setregid(int __rgid, int __egid);

    int setegid(int __gid);

    int fork();

    int vfork();

    Pointer ttyname(int __fd);

    int ttyname_r(int __fd, ByteBuffer __buf, NativeSize __buflen);

    int isatty(int __fd);

    int ttyslot();

    int link(String __from, String __to);

    int linkat(int __fromfd, String __from, int __tofd, String __to, int __flags);

    int symlink(String __from, String __to);

    NativeLong readlink(String __path, ByteBuffer __buf, NativeSize __len);

    int symlinkat(String __from, int __tofd, String __to);

    NativeLong readlinkat(int __fd, String __path, ByteBuffer __buf, NativeSize __len);

    int unlink(String __name);

    int unlinkat(int __fd, String __name, int __flag);

    int rmdir(String __path);

    int tcgetpgrp(int __fd);

    int tcsetpgrp(int __fd, int __pgrp_id);

    Pointer getlogin();

    int getlogin_r(ByteBuffer __name, NativeSize __name_len);

    int setlogin(String __name);

    int getopt(int ___argc, String ___argv[], String __shortopts);

    int gethostname(ByteBuffer __name, NativeSize __len);

    int sethostname(String __name, NativeSize __len);

    int sethostid(NativeLong __id);

    int getdomainname(ByteBuffer __name, NativeSize __len);

    int setdomainname(String __name, NativeSize __len);

    int vhangup();

    int revoke(String __file);

    int profil(ShortBuffer __sample_buffer, NativeSize __size, NativeSize __offset, int __scale);

    int acct(String __name);

    Pointer getusershell();

    void endusershell();

    void setusershell();

    int daemon(int __nochdir, int __noclose);

    int chroot(String __path);

    Pointer getpass(String __prompt);

    int fsync(int __fd);

    NativeLong gethostid();

    void sync();

    int getpagesize();

    int getdtablesize();

    int truncate(String __file, NativeLong __length);

    int ftruncate(int __fd, NativeLong __length);

    int brk(Pointer __addr);

    Pointer sbrk(IntBuffer __delta);

    NativeLong syscall(NativeLong __sysno, Object... varargs);

    int lockf(int __fd, int __cmd, NativeLong __len);

    int fdatasync(int __fildes);

    Pointer ctermid(ByteBuffer __s);

    int ioctl(int __fd, NativeLong __request, Object... varargs);

    public static final GlobalPointerType<ByteByReference> optarg = new GlobalPointerType<ByteByReference>(CLibrary.JNA_NATIVE_LIB, ByteByReference.class, "optarg");
    public static final GlobalInt optind = new GlobalInt(CLibrary.JNA_NATIVE_LIB, "optind");
    public static final GlobalInt opterr = new GlobalInt(CLibrary.JNA_NATIVE_LIB, "opterr");
    public static final GlobalInt optopt = new GlobalInt(CLibrary.JNA_NATIVE_LIB, "optopt");

    public static class mmsghdr extends PointerType {
        public mmsghdr(Pointer address) {
            super(address);
        }

        public mmsghdr() {
            super();
        }
    }

    public static class iface extends PointerType {
        public iface(Pointer address) {
            super(address);
        }

        public iface() {
            super();
        }
    }
}
