package com.amazonaws.sfc.canbus.jna;

import com.ochafik.lang.jnaerator.runtime.NativeSize;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * Structure for scatter/gather I/O.<br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a> */
@SuppressWarnings({"unused", "SpellCheckingInspection"})
public class iovec extends Structure {
	/**
	 * Pointer to data.<br>
	 * C type : void*
	 */
	public Pointer iov_base;
	/** Length of data. */
	public NativeSize iov_len;
	public iovec() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("iov_base", "iov_len");
	}
	/**
	 * @param iov_base Pointer to data.<br>
	 * C type : void*<br>
	 * @param iov_len Length of data.
	 */
	public iovec(Pointer iov_base, NativeSize iov_len) {
		super();
		this.iov_base = iov_base;
		this.iov_len = iov_len;
	}
	public static class ByReference extends iovec implements Structure.ByReference {
		
	};
	public static class ByValue extends iovec implements Structure.ByValue {
		
	};
}
