package com.amazonaws.sfc.canbus.jna;

import com.ochafik.lang.jnaerator.runtime.NativeSize;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;
/**
 * Structure describing messages sent by<br>
 * `sendmsg' and received by `recvmsg'.<br>
 * This file was autogenerated by <a href="https://github.com/nativelibs4java/JNAerator">JNAerator</a> */
@SuppressWarnings({"unused", "SpellCheckingInspection"})
public class msghdr extends Structure {
	/**
	 * Address to send to/receive from.<br>
	 * C type : void*
	 */
	public Pointer msg_name;
	/**
	 * Length of address data.<br>
	 * C type : socklen_t
	 */
	public int msg_namelen;
	/**
	 * Vector of data to send/receive into.<br>
	 * C type : iovec*
	 */
	public iovec.ByReference msg_iov;
	/** Number of elements in the vector. */
	public NativeSize msg_iovlen;
	/**
	 * Ancillary data (eg BSD filedesc passing).<br>
	 * C type : void*
	 */
	public Pointer msg_control;
	/**
	 * Ancillary data buffer length.<br>
	 * !! The type should be socklen_t but the<br>
	 * definition of the kernel is incompatible<br>
	 * with this.
	 */
	public NativeSize msg_controllen;
	/** Flags on received message. */
	public int msg_flags;
	public msghdr() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("msg_name", "msg_namelen", "msg_iov", "msg_iovlen", "msg_control", "msg_controllen", "msg_flags");
	}
	/**
	 * @param msg_name Address to send to/receive from.<br>
	 * C type : void*<br>
	 * @param msg_namelen Length of address data.<br>
	 * C type : socklen_t<br>
	 * @param msg_iov Vector of data to send/receive into.<br>
	 * C type : iovec*<br>
	 * @param msg_iovlen Number of elements in the vector.<br>
	 * @param msg_control Ancillary data (eg BSD filedesc passing).<br>
	 * C type : void*<br>
	 * @param msg_controllen Ancillary data buffer length.<br>
	 * !! The type should be socklen_t but the<br>
	 * definition of the kernel is incompatible<br>
	 * with this.<br>
	 * @param msg_flags Flags on received message.
	 */
	public msghdr(Pointer msg_name, int msg_namelen, iovec.ByReference msg_iov, NativeSize msg_iovlen, Pointer msg_control, NativeSize msg_controllen, int msg_flags) {
		super();
		this.msg_name = msg_name;
		this.msg_namelen = msg_namelen;
		this.msg_iov = msg_iov;
		this.msg_iovlen = msg_iovlen;
		this.msg_control = msg_control;
		this.msg_controllen = msg_controllen;
		this.msg_flags = msg_flags;
	}
	public static class ByReference extends msghdr implements Structure.ByReference {
		
	};
	public static class ByValue extends msghdr implements Structure.ByValue {
		
	};
}
