/*
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.SPDX-License-Identifier: MIT-0
 */

package com.amazonaws.sfc.ads.protocol

class AdsException(message: String, result: Int = 0) :
    Exception("$message${if (result != 0) ", $result, ${adsErrorString(result)}" else ""}")

fun adsErrorString(result: Int) = when (result) {
    0 -> "No error"
    1 -> "Internal error"
    2 -> "No rea-time"
    3 -> "Allocation locked - memory error"
    4 -> "Mailbox full"
    5 -> "Wrong HMSG"
    6 -> "Target port not found"
    7 -> "Target computer not found"
    8 -> "Unknown command ID"
    9 -> "Invalid task ID"
    10 -> "No IO"
    11 -> "Unknown AMs command"
    12 -> "Win 32 error"
    13 -> "Port not connected"
    14 -> "Invalid AMS length"
    15 -> "Invalid AMS Net ID"
    16 -> "Installation level is too low"
    17 -> "No debug available"
    18 -> "Port disabled"
    19 -> "Port already connected"
    20 -> "AMS Sync Win32 error"
    21 -> "AMS Sync Timeout"
    22 -> "Ads Sync Ads error"
    23 -> "No index map for AMS Sync available."
    24 -> "Invalid AMD port"
    25 -> "No memory"
    26 -> "TCP send error"
    27 -> "Host unreachable"
    28 -> "Invalid AMS fragment"
    29 -> "TLS send error"
    30 -> "Access denied"
    1792 -> "General device error."
    1793 -> "Service is not supported by server"
    1794 -> "Invalid index group"
    1795 -> "Invalid index offset"
    1796 -> "Reading or writing not permitted"
    1797 -> "Parameter size not correct"
    1798 -> "Invalid parameter value(s)"
    1799 -> "Device is not in a ready state"
    1800 -> "Device is busy"
    1801 -> "Invalid operating system context"
    1802 -> "Insufficient memory"
    1803 -> "Invalid parameter value(s)"
    1804 -> "Not found files (...)"
    1805 -> "Syntax error in file or command"
    1806 -> "Objects do not match"
    1807 -> "Object already exists"
    1808 -> "Symbol not found"
    1809 -> "Symbol version invalid"
    1810 -> "Server is in invalid state"
    1811 -> "AdsTransMode not supported"
    1812 -> "Notification handle is invalid"
    1813 -> "Notification client not registered"
    1814 -> "No further handle available"
    1815 -> "Notification size too large"
    1816 -> "Device not initialized"
    1817 -> "Device has a timeout"
    1818 -> "Query interface failed"
    1819 -> "Wrong interface failed"
    1820 -> "Class ID is invalid"
    1821 -> "Object ID is invalid"
    1822 -> "Request is pending"
    1823 -> "Request is aborted"
    1824 -> "Signal warning"
    1825 -> "Invalid array index"
    1826 -> "Symbol not active"
    1827 -> "Access denied"
    1828 -> "Missing license"
    1829 -> "License expired"
    1830 -> "License exceeded"
    1831 -> "Invalid license"
    1832 -> "License problem: System ID is invalid"
    1833 -> "License not limited in time"
    1834 -> "License problem: Time in the future"
    1835 -> "License period too long"
    1836 -> "Exception at system startup"
    1837 -> "License file read twice"
    1838 -> "Invalid signature"
    1839 -> "Invalid certificate"
    1840 -> "Public key not known from OEM"
    1841 -> "License not valid for this system ID"
    1842 -> "Demo license prohibited"
    1843 -> "Invalid function ID"
    1844 -> "Invalid alignment"
    1845 -> "Outside the valid range"
    1846 -> "Invalid platform level"
    1848 -> "Context – forward to dispatch level"
    1849 -> "Context – forward to real-time"
    1856 -> "Client error"
    1857 -> "Service contains an invalid parameter"
    1858 -> "Polling list is empty"
    1859 -> "Var connection already in use"
    1860 -> "The called ID is already in use"
    1861 -> "Timeout has occurred"
    1862 -> "Error in Win32 subsystem"
    1863 -> "Invalid client timeout value"
    1864 -> "Port not open"
    1865 -> "No AMS address"
    1872 -> "Internal error in Ads sync"
    1873 -> "Hash table overflow"
    1874 -> "Key not found in the table"
    1875 -> "No symbols in the cache"
    1876 -> "Invalid response received"
    1877 -> "Sync Port is locked"
    else -> "Unknown Error"
}
